# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_pb2 as trading__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitExchange = channel.unary_unary(
                '/trading.TradingService/InitExchange',
                request_serializer=trading__pb2.InitExchangeRequest.SerializeToString,
                response_deserializer=trading__pb2.InitExchangeResponse.FromString,
                _registered_method=True)
        self.GetQuote = channel.unary_unary(
                '/trading.TradingService/GetQuote',
                request_serializer=trading__pb2.GetQuoteRequest.SerializeToString,
                response_deserializer=trading__pb2.GetQuoteResponse.FromString,
                _registered_method=True)
        self.SubmitOrder = channel.unary_unary(
                '/trading.TradingService/SubmitOrder',
                request_serializer=trading__pb2.OrderRequest.SerializeToString,
                response_deserializer=trading__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.ViewPortfolio = channel.unary_unary(
                '/trading.TradingService/ViewPortfolio',
                request_serializer=trading__pb2.ViewPortfolioRequest.SerializeToString,
                response_deserializer=trading__pb2.ViewPortfolioResponse.FromString,
                _registered_method=True)


class TradingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InitExchange(self, request, context):
        """初始化交易所账户：清空持仓，设置初始资金
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuote(self, request, context):
        """获取某只股票的实时报价
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitOrder(self, request, context):
        """提交订单（买入 / 卖出）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewPortfolio(self, request, context):
        """查看账户持仓、现金、持仓价值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.InitExchange,
                    request_deserializer=trading__pb2.InitExchangeRequest.FromString,
                    response_serializer=trading__pb2.InitExchangeResponse.SerializeToString,
            ),
            'GetQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuote,
                    request_deserializer=trading__pb2.GetQuoteRequest.FromString,
                    response_serializer=trading__pb2.GetQuoteResponse.SerializeToString,
            ),
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=trading__pb2.OrderRequest.FromString,
                    response_serializer=trading__pb2.TradeResponse.SerializeToString,
            ),
            'ViewPortfolio': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewPortfolio,
                    request_deserializer=trading__pb2.ViewPortfolioRequest.FromString,
                    response_serializer=trading__pb2.ViewPortfolioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/InitExchange',
            trading__pb2.InitExchangeRequest.SerializeToString,
            trading__pb2.InitExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetQuote',
            trading__pb2.GetQuoteRequest.SerializeToString,
            trading__pb2.GetQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/SubmitOrder',
            trading__pb2.OrderRequest.SerializeToString,
            trading__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewPortfolio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/ViewPortfolio',
            trading__pb2.ViewPortfolioRequest.SerializeToString,
            trading__pb2.ViewPortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
